# =========================================================
# Profile: DEV (server development dengan PostgreSQL)
# =========================================================

# -------------------------
# PostgreSQL Database
# -------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/rest_template_dev
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# update: update schema tanpa hapus data yang sudah ada
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

# -------------------------
# JPA
# -------------------------
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# -------------------------
# Logging Level
# -------------------------
logging.level.com.example.template=DEBUG
logging.level.org.springframework.security=INFO
